version: '3.8'
services:
  routing:
    build: ./routing-container
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  textgen:
    build: ./textgen-container
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
